### ISSUE TITLE
error loading module 'input' from file '/usr/local/lib/lua/5.2/input.so'

### ISSUE THREAD

**Issue by ubx** [max1220/lua-input#2]
Hi

Installed and cross compiled `lua-input` according to the Manual installation on this Linux system:
```
uname -a
Linux (none) 4.1.15-00838-g349fbf5767c #90 SMP PREEMPT Thu Sep 15 15:12:23 CST 2022 armv7l GNU/Linux
```
Start the Lua interpreter:
```

~ # lua
Lua 5.2.2  Copyright (C) 1994-2013 Lua.org, PUC-Rio
> local input = require("lua-input")
error loading module 'input' from file '/usr/local/lib/lua/5.2/input.so':
        dynamic libraries not enabled; check your Lua installation
stack traceback:
        [C]: in ?
        [C]: in function 'require'
        /usr/local/share/lua/5.2/lua-input/init.lua:1: in main chunk
        [C]: in function 'require'
        stdin:1: in main chunk
        [C]: in ?
```

Any hint to solve this problem?

BTW, it works fine on a Raspberry Pi (Linux 5.10)

**Comment by max1220** [comment]
I'm sorry for the late response. 
Did you provide a correct LUA_LIBDIR and LUA_INCDIR when compiling? The defaults are for Lua5.1.
Also, are you using a stand-alone Lua installation, on a regular Linux installation, or an embedded Lua interpreter in another language?
```
dynamic libraries not enabled; check your Lua installation
```
That's kind of strange, as my library does nothing special in that regard(it's just a normal Lua library). Do other C libraries load normally?

**Comment by ubx** [comment]
Hi Max

> Did you provide a correct LUA_LIBDIR and LUA_INCDIR when compiling? The defaults are for Lua5.1.

Yes

> Also, are you using a stand-alone Lua installation, on a regular Linux installation, or an embedded Lua interpreter in another language?

The installation is on a Kobo eReader.

After tracing down the problem and searching the web, I came to the conclusion that the function dlopen() seems not to be supported on this platform.

In the meantime, I solved my problem with a simple bash script! So I think it is a waste of time to further investigate this problem, and you may close the issue.

**Comment by max1220** [comment]
Without further investigation - You're probably right.

Lua embedded in other applications sometimes disables loading C modules via the `require()`/`dlopen()` mechanism for security reasons:
Loading a shared library is basically like starting another application, with all the implicit permissions that comes with.
